version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongoData:/var/lib/mongo/data
    ports:
      - "27017:27017"
    restart: always
  api:
    build: "./"
    container_name: b2w-test
    command: ["yarn", "dev:server"]
    ports:
      - "3333:3333"
    links:
      - mongo
    depends_on:
      - mongo
    restart: always